import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.manifold import TSNE
from sklearn.cluster import DBSCAN
import plotly.express as px
import pandas as pd

class_names = [
    "cabinet",
    "bookshelf",
    "shelf",
    "storage cabinet",
    "whiteboard",
    "heater",
    "storage rack",
    "kitchen cabinet",
    "office table",
    "cupboard",
    "crate",
    "pipe storage rack",
    "open cabinet",
    "file cabinet",
    "laboratory cabinet",
    "kitchen unit",
    "office desk",
    "electrical control panel",
    "coffee table",
    "bar counter",
    "kitchen sink",
    "electrical panel",
    "closet",
    "conference table",
    "book shelf",
    "dresser",
    "bathroom stall",
    "coat rack",
    "bedside table",
    "door",
    "blinds",
    "window",
    "ceiling light",
    "structure",
    "roof",
    "sink",
    "windowframe",
    "blind",
    "suspended ceiling",
    "shower floor",
    "bathtub",
    "glass wall",
    "ceiling ventilator",
    "raised floor",
    "stairs",
    "radiator",
    "sliding door",
    "vent",
    "ventilation pipe",
    "ceiling pipe",
    "electric duct",
    "staircase railing",
    "brick wall",
    "skylight",
    "electrical box",
    "shower ceiling",
    "vertical blinds",
    "tap",
    "exhaust duct",
    "ventilation duct",
    "shower",
    "partition wall",
    "bathroom floor",
    "shower head",
    "socket",
    "electrical cabinet",
    "curtain rod",
    "window pane",
    "air conditioning",
    "wall strip",
    "shower screen",
    "sliding door frame",
    "blind rails",
    "backsplash",
    "cable duct",
    "kitchen back splash",
    "recessed shelve",
    "switchboard cabinet",
    "exit sign",
    "fireplace surround",
    "balcony door",
    "main switchboard",
    "blinds rod",
    "sill",
    "ceiling lamp bar",
    "curtain frame",
    "wooden post",
    "baseboard",
    "doorway",
    "shower faucet",
    "emergency light",
    "blind rod",
    "shower tray",
    "shower cubicle",
    "shower seating",
    "toilet flush button",
    "shower door frame",
    "fluorescent lamp",
    "cabinet frame",
    "door vent",
    "door lamp",
    "wood panel",
    "overhead shower",
    "emergency shower",
    "shower glass",
    "shower arm",
    "panelboard",
    "wall paper",
    "recessed shower shelve",
    "water tap",
    "water meter",
    "electrical pipe",
    "wall cord cover",
    "column",
    "water meter cover",
    "socket box",
    "cabinet side panel",
    "conduit pipe",
    "network socket",
    "wall outlet",
    "cabinet base panel",
    "shower valve",
    "flush tank",
    "flush",
    "drain",
    "radiator pipe",
    "cabinet top panel",
    "flush plate",
    "valve",
    "ceiling lamp",
    "table",
    "curtain",
    "office chair",
    "chair",
    "monitor",
    "object",
    "box",
    "sofa",
    "tv",
    "plant",
    "bed",
    "computer tower",
    "blanket",
    "trash can",
    "window sill",
    "books",
    "trash bin",
    "machine",
    "wardrobe",
    "jacket",
    "desk",
    "pillar",
    "bag",
    "towel",
    "carpet",
    "keyboard",
    "refrigerator",
    "pillow",
    "backpack",
    "rug",
    "suitcase",
    "window blind",
    "blackboard",
    "microwave",
    "shower curtain",
    "pedestal fan",
    "printer",
    "stool",
    "ladder",
    "picture",
    "fume hood",
    "toilet",
    "rack",
    "book",
    "experiment bench",
    "bottle",
    "air conditioner",
    "oven",
    "rolling cart",
    "beverage crate",
    "mirror",
    "power socket",
    "bucket",
    "shoe rack",
    "bench",
    "shoes",
    "telephone",
    "basket",
    "mattress",
    "stove",
    "gym mat",
    "cardboard box",
    "bin",
    "pc",
    "objects",
    "milling machine",
    "photocopy machine",
    "tv stand",
    "lab equipment",
    "laboratory bench",
    "poster",
    "trolley",
    "scientific equipment",
    "lab machine",
    "whiteboards",
    "standing lamp",
    "coat",
    "washing machine",
    "laptop",
    "cushion",
    "hydraulic press",
    "office cabinet",
    "beanbag",
    "fan",
    "medical appliance",
    "dishwasher",
    "copier",
    "3d printer",
    "arm chair",
    "cart",
    "flat panel display",
    "file folder",
    "coffee machine",
    "cardboard",
    "floor mounted air conditioner",
    "television",
    "couch",
    "headboard",
    "stage",
    "exhaust fan",
    "drying rack",
    "interactive board",
    "laundry basket",
    "cables",
    "vacuum cleaner",
    "plant pot",
    "coffee maker",
    "wire tray",
    "training equipment",
    "comforter",
    "work bench",
    "bathroom cabinet",
    "fridge",
    "rolling blinds",
    "painting",
    "projector",
    "hose",
    "storage trolley",
    "coat hanger",
    "laboratory equipment",
    "duvet",
    "sofa chair",
    "dining chair",
    "tv screen",
    "table lamp",
    "fume cupboard",
    "paper towel dispenser",
    "floor lamp",
    "nightstand",
    "kettle",
    "classroom table",
    "bedsheet",
    "bottles",
    "steel beam",
    "treadmill",
    "light switch",
    "clothes dryer",
    "bicycle",
    "speaker",
    "light",
    "container",
    "armchair",
    "l-shaped sofa",
    "pinboard",
    "shower partition",
    "fire extinguisher",
    "computer desk",
    "lounge chair",
    "lamp",
    "office visitor chair",
    "garage door",
    "range hood",
    "power strip",
    "ping pong table",
    "rolling chair",
    "tripod",
    "shirt",
    "cloth rack",
    "roller blinds",
    "cable",
    "shoe",
    "air pipe",
    "decoration",
    "cloth hangers",
    "urinal",
    "ceiling vent",
    "mug",
    "folder",
    "frame",
    "bar stool",
    "compressor",
    "tile wall",
    "seat",
    "mouse",
    "loft bed",
    "foosball table",
    "indoor crane",
    "squat rack",
    "umbrella",
    "high stool",
    "pallet cage",
    "backdrop",
    "tablecloth",
    "robot car",
    "overhead projector",
    "folding screen",
    "cpu",
    "standing poster",
    "dining table",
    "high table",
    "cup",
    "smoke detector",
    "desk fan",
    "banner",
    "microscope",
    "drum",
    "standing fan",
    "coat stand",
    "barbecue grill",
    "console",
    "room divider",
    "side table",
    "medical machine",
    "paper bag",
    "toilet paper",
    "wall cabinet",
    "christmas tree",
    "kitchen towel",
    "bathroom mat",
    "crates",
    "guitar",
    "luggage",
    "monitor cover",
    "floor sofa",
    "tray",
    "rolling table",
    "folding room divider",
    "desk lamp",
    "storage box",
    "freezer display counter",
    "broom",
    "vr setup",
    "yoga mat",
    "projector screen",
    "canvas",
    "surfboard",
    "water filter",
    "racing simulator",
    "car door",
    "interactive whiteboard",
    "bath cabinet",
    "pot",
    "chairs",
    "file organizer",
    "standing banner",
    "wheelchair",
    "jug",
    "tool rack",
    "shoes holder",
    "pan",
    "mat",
    "rice cooker",
    "curtains",
    "tote bag",
    "jar",
    "toilet brush",
    "wall lamp",
    "paper towel",
    "cleaning trolley",
    "plate",
    "storage shelf",
    "high bench",
    "blackboard frame",
    "hose pipe",
    "babyfoot table",
    "dish rack",
    "folders",
    "foldable closet",
    "vase",
    "bath tub",
    "bed frame",
    "air purifier",
    "cubicle door",
    "file rack",
    "exercise ball",
    "cutting board",
    "file binder",
    "bathroom counter",
    "dustbin",
    "plastic case",
    "sweater",
    "janitor cart",
    "slippers",
    "laptop stand",
    "boots",
    "plank",
    "ottoman",
    "cord cover",
    "binder",
    "small cabinet",
    "duct",
    "folding sofa",
    "towel radiator",
    "paper organizer",
    "climbing wall",
    "wooden frame",
    "kitchen shelf",
    "faucet",
    "bathroom shelf",
    "light panel",
    "toolbox",
    "headphones",
    "soap dispenser",
    "ac system",
    "phone",
    "desk organizer",
    "toy",
    "bottle crate",
    "microwave oven",
    "rolled paper",
    "spray bottle",
    "helmet",
    "trashcan",
    "bowl",
    "tower pc",
    "trolley table",
    "exhaust pipe",
    "shelf trolley",
    "copy machine",
    "filer organizer",
    "curtain rail",
    "grab bar",
    "information board",
    "piano",
    "garage shelf",
    "hanging closet",
    "instant pot",
    "wall beam",
    "notebook",
    "basin",
    "table football",
    "whiteboard eraser",
    "paper shredder",
    "notice board",
    "plastic bag",
    "paper tray",
    "metal board",
    "sheet",
    "mop",
    "plumbing pipe",
    "toaster",
    "shower pan",
    "locker",
    "air fryer",
    "hanger",
    "tv mount",
    "tissue box",
    "information stand",
    "floor scrubber",
    "weighing scale",
    "workbench",
    "slipper",
    "toaster oven",
    "clock",
    "lab materials",
    "bike",
    "dumbbell",
    "paper rack",
    "drawer",
    "rolling curtain",
    "sink counter",
    "headphone",
    "fitted wardrobe",
    "wall hanging",
    "wall clock",
    "jerry can",
    "wooden plank",
    "tv table",
    "shower cabin",
    "scarf",
    "bathroom rack",
    "tube",
    "appliance",
    "ventilator",
    "spotlight",
    "fabric",
    "standing clothes hanger",
    "paper bin",
    "cooker hood",
    "reflection",
    "barber chair",
    "chandelier",
    "filing cabinet",
    "bench press",
    "suit cover",
    "espresso machine",
    "outlet",
    "standing light",
    "rolling shelf cart",
    "trousers",
    "water dispenser",
    "serving trolley",
    "file",
    "guitar bag",
    "electric hob",
    "surfsuit",
    "magazine stand",
    "light stand",
    "toilet paper dispenser",
    "water heater",
    "storage container",
    "softbox",
    "vaccum cleaner",
    "recliner",
    "water kettle",
    "pen holder",
    "built-in shelf",
    "photocopier",
    "glass bottle",
    "mini fridge",
    "picture frame",
    "ceiling fan",
    "smoke alarm",
    "papasan chair",
    "medicine cabinet",
    "foot rest",
    "whiteboard stand",
    "wooden pallet",
    "shopping bag",
    "camping bed",
    "power panel",
    "bagpack",
    "decoration piece",
    "trolley tray",
    "shower rug",
    "floor mat",
    "bar table",
    "study table",
    "control panel",
    "headset",
    "lectern",
    "oven range",
    "shopping trolley",
    "step stool",
    "cable pathway",
    "tv console",
    "electronic appliance",
    "lab coat",
    "grill",
    "pack",
    "shoe cabinet",
    "portable fan",
    "cylinder",
    "glass shelf",
    "panel",
    "screen",
    "pelican case",
    "bedframe",
    "hat",
    "cable rack",
    "shelving cart",
    "computer table",
    "sheep doll",
    "monitor stand",
    "magazine",
    "equipment",
    "ottoman chair",
    "mouse pad",
    "mirror frame",
    "gym bag",
    "floor cushion",
    "calendar",
    "beach umbrella",
    "human skeleton",
    "paper cutter",
    "labcoat",
    "bath counter",
    "table cloth",
    "plastic bottle",
    "tower fan",
    "easel",
    "jeans",
    "ceiliing",
    "white board",
    "tablet",
    "studio light",
    "bedside lamp",
    "equipment cover",
    "bathroom sink",
    "bottles case",
    "toilet paper holder",
    "briefcase",
    "pants",
    "air conditioner tower",
    "canister",
    "laundry hanger",
    "stuffed animal",
    "sheets",
    "clothes rack",
    "multifunction printer",
    "gym mattress",
    "metal rack",
    "wall unit",
    "messenger bag",
    "kitchen counter top",
    "barrel",
    "countertop",
    "food container",
    "tool organizer",
    "sink pipe",
    "plastic box",
    "toilet seat",
    "tv board",
    "lab fridge",
    "folding chair",
    "dish drainer",
    "hand shower",
    "flip flops",
    "plate rack",
    "filter jug",
    "dog bed",
    "boot",
    "sack",
    "mobile tv stand",
    "bedside shelf",
    "robot vacuum cleaner",
    "stapler",
    "cable conduit",
    "water bottle",
    "shower hose",
    "footstool",
    "teddy bear",
    "shower curtain rod",
    "bedside cabinet",
    "storage bin",
    "laboratory power supply",
    "flower pot",
    "watering can",
    "kitchenware",
    "folded table",
    "projection curtain",
    "cover",
    "rolling trolley",
    "whiteboard mount",
    "electric kettle",
    "tree trunk",
    "softbox light",
    "computer",
    "exhaust hood",
    "spice rack",
    "bench stool",
    "computer monitor",
    "work station",
    "flipchart",
    "switch",
    "flush button",
    "push cart",
    "window head",
    "laundry rack",
    "stack of chairs",
    "cooking pot",
    "router",
    "cardbox",
    "wine rack",
    "file storage",
    "styrofoam box",
    "podium",
    "deck chair",
    "wall board",
    "night stand",
    "led ceiling fan",
    "tool box",
    "wall painting",
    "bean bag",
    "recesssed shelf",
    "globe",
    "garbage bin",
    "ornament",
    "game console",
    "tshirt",
    "plastic container",
    "projection screen",
    "bathrobe",
    "machine container",
    "skiboard",
    "paper stapler",
    "water jug",
    "wall shelf",
    "speaker stand",
    "rolling bag",
    "hair dryer",
    "dish drying rack",
    "dumbbell case",
    "soap bottle",
    "lid",
    "drum set",
    "shower tub",
    "small dresser",
    "tv trolley",
    "tubelight",
    "cupoard",
    "paper roll",
    "file holder",
    "ventilation",
    "hand bag",
    "bulletin board",
    "ring light",
    "tool",
    "carton",
    "delivery bag",
    "towel heater",
    "kitchen pot",
    "electronic device",
    "mirror cabinet",
    "metal sheet",
    "stair",
    "tabletop",
    "duffel bag",
    "bottle carrier",
    "floor couch",
    "step",
    "tv receiver",
    "hairdryer",
    "water bubbler",
    "skateboard",
    "ball",
    "cable raceway",
    "high chair",
    "towel warmer",
    "suit",
    "t shirt",
    "workshop tool",
    "cable roller",
    "shopping basket",
    "headrail",
    "bath mat",
    "cap",
    "chopping board",
    "woofer",
    "water pipe",
    "wooden palette",
    "television stand",
    "envelope",
    "carboard box",
    "planter",
    "power cabinet",
    "brush",
    "toilet paper rolls",
    "cloth hanger",
    "microphone",
    "stack of paper",
    "ironing board",
    "document tray",
    "hole puncher",
    "chemical canister",
    "shoe box",
    "oscilloscope",
    "upholstered bench",
    "mini oven",
    "cat bed",
    "towel holder",
    "sign",
    "sidetable",
    "camera",
    "jerrycan",
    "apron",
    "dog bowl",
    "doormat",
    "cable panel",
    "centrifuge",
    "sponge",
    "document organizer",
    "light fixture",
    "platform trolley",
    "rolled poster",
    "rolling stand",
    "photo frame",
    "cloth piece",
    "gloves",
    "flag",
    "hand towel",
    "web cam",
    "running shoes",
    "paperbag",
    "mixer",
    "trash bag",
    "center table",
    "laptop bag",
    "folding umbrella",
    "crate trolley",
    "dustpan",
    "table fan",
    "portable ladder",
    "gym ball",
    "document holder",
    "glass pane",
    "high pressure cylinder",
    "laboratory pellet press",
    "first aid kit",
    "organizer",
    "weight plate",
    "laundry hamper",
    "plushie",
    "luggage bag",
    "stepladder",
    "tower ventilator",
    "boiler",
    "knife set",
    "electric stove",
    "stand",
    "flower",
    "kitchen wall",
    "projector holder",
    "case",
    "piano stool",
    "pressure cooker",
    "kitchen robot",
    "plush doll",
    "kitchen cloth",
    "cable spool",
    "sit-up pillow",
    "can",
    "fireplace",
    "shelve",
    "bladeless fan",
    "pegboard",
    "door mat",
    "plate weights",
    "sandals",
    "laptop table",
    "foreman grill",
    "rolling cabinet",
    "powerstrip",
    "chemical barrel",
    "power socket unit",
    "surfing board",
    "baby stroller",
    "magazine rack",
    "rolled blanket",
    "vice",
    "wash basin",
    "pc tower",
    "drone",
    "clothes drying stand",
    "skeleton",
    "webcam",
    "short table",
    "washbasin",
    "kitchen hood",
    "gym plate",
    "scale",
    "notice",
    "bedpost",
    "weight scale",
    "plant pot mat",
    "mop basin",
    "bananas",
    "chemical container",
    "safe box",
    "sneakers",
    "milk jug",
    "piano chair",
    "rolling blind",
    "baseball cap",
    "christmas ornament",
    "blender",
    "pumper",
    "rucksack",
    "gas tank",
    "sandal",
    "suit bag",
    "intercom",
    "stereo",
    "toiletry",
    "table mat",
    "exhaustive fan",
    "socket extender",
    "dispenser bottle",
    "medical stool",
    "railing",
    "belt",
    "shower sink",
    "wastebin",
    "chemical bottle",
    "folding table",
    "shower tap",
    "wall hanger",
    "model car",
    "plug",
    "microphone stand",
    "cd player",
    "charcoal bag",
    "pitcher",
    "power outlet",
    "cabel",
    "dust pan",
    "soap",
    "bar",
    "photo",
    "detergent bottle",
    "file tray",
    "guitar case",
    "eraser",
    "mousepad",
    "iron",
    "wire",
    "rag",
    "scooter",
    "egg carton",
    "marker",
    "water pitcher",
    "cable wheel",
    "billboard",
    "cooking pan",
    "hanging light fixture",
    "sauce pan",
    "storage",
    "roomba",
    "rolled cable",
    "barbell",
    "chrismas tree",
    "rolled projection screen",
    "wooden crate",
    "mini shelf",
    "shampoo bottle",
    "paper towel package",
    "bracket",
    "umbrella stand",
    "heater tube",
    "loafers",
    "kettlebell",
    "scanner",
    "paper holder",
    "wifi router",
    "door handle",
    "oven gloves",
    "alarm",
    "file stack",
    "tissue dispenser stand",
    "wall hook",
    "power extension",
    "sauce rack",
    "tape dispenser",
    "water bucket",
    "mirror light",
    "bathroom holder",
    "candle",
    "toothbrush",
    "dumbell",
    "pouch",
    "tea pot",
    "tennis racket",
    "rolled backdrop",
    "glove dispenser",
    "drill",
    "watering pot",
    "laptop case",
    "pot lid",
    "sofa cushion",
    "plastic tray",
    "pull up bar",
    "paper tube",
    "charger",
    "packet of toilet paper",
    "desk power strip",
    "insulated can",
    "extension cord",
    "vr headset",
    "closet rail",
    "stick",
    "remote control",
    "wood piece",
    "metal frame",
    "blinds rail",
    "cone",
    "kitchen knives",
    "mixer machine",
    "kitchen utensil",
    "seat cushion",
    "glass",
    "power switch",
    "floor wiper",
    "shower handle",
    "totebag",
    "mixer glass",
    "package",
    "sign board",
    "laundry vent",
    "long pillow",
    "plastic drum",
    "fruit",
    "stuffed toy",
    "pencil holder",
    "hand soap dispenser",
    "pen tray",
    "recycle bag",
    "kitchen stove",
    "glass plate",
    "pen",
    "facsimile",
    "dvd player",
    "folder oragnizer",
    "shower mat",
    "photoframe",
    "headphone case",
    "tissue",
    "tea box",
    "air heater",
    "wooden stick",
    "bed cover",
    "hand washing soap",
    "pizza box",
    "rod",
    "wooden board",
    "clothes hangers",
    "shower gel",
    "foot massager",
    "stuffed animal door insulator",
    "extension chord reel",
    "thermostat",
    "key hanger",
    "alligator clips",
    "folded cardboard",
    "dish washer",
    "towel paper dispenser",
    "socket strip",
    "flip flop",
    "metal mount",
    "wall calendar",
    "brief",
    "wall coat hanger",
    "gas cylinder",
    "knife holder",
    "badminton racket",
    "pole stand",
    "laptop sleeve",
    "chessboard",
    "bread toaster",
    "pencil case",
    "heels",
    "kitchen drawer",
    "candle holder",
    "barstool",
    "soap dish",
    "dish soap bottle",
    "oven panel",
    "plush toy",
    "guillotine paper cutter",
    "rope",
    "cleaning mop",
    "french press",
    "wok pan",
    "paper towel roll",
    "toilet paper roll",
    "monitor support",
    "remote",
    "folded bag",
    "paper ram",
    "bedisde table",
    "prosthetic leg",
    "chart",
    "tool case",
    "dartboard",
    "package bag",
    "electric guitar",
    "emergency kit",
    "kitchen glove",
    "recycle bin",
    "beaker stand",
    "handbag",
    "safe",
    "stabilizer",
    "tub",
    "dvd",
    "satchel",
    "electric toothbrush",
    "tv remote",
    "notepad",
    "hand washing soap dispenser",
    "penholder",
    "toothpaste",
    "sculpture",
    "basketball",
    "cooling pad",
    "electric pot",
    "pencil cup",
    "plastic can",
    "flipflop",
    "hygiene product",
    "tupperware",
    "cosmetic bag",
    "leather mattress",
    "purse",
    "power cord",
    "pallet",
    "running shoe",
    "floor cleaner",
    "utensil holder",
    "piano book",
    "calculator",
    "paper stack",
    "first aid cabinet",
    "hanging deer skull",
    "wall coat rack",
    "glasses case",
    "salad spinner",
    "pamphlet",
    "knife",
    "detergent",
    "device",
    "kitchen appliance",
    "chain",
    "toothbrush holder",
    "pencils cup",
    "insulated coffee mug",
    "frying pan",
    "paper box",
    "knife block",
    "desk light",
    "binding machine",
    "food",
    "shoe case",
    "rolling mat",
    "wooden brush",
    "neck pillow",
    "package of paper",
    "water boiler",
    "telephone stand",
    "tape",
    "cosmetic pouch",
    "bag of oranges",
    "caution board",
    "switchboard",
    "power adapter",
    "wooden plan",
    "camera bag",
    "garbage bin cover",
    "citrus juicer",
    "multiplug",
    "shade",
    "statue",
    "cutboard",
    "pepper mill",
    "control unit",
    "kitchen ceiling",
    "grill pan",
    "surveillance camera",
    "cleaning brush",
    "robot vaccuum cleaner",
    "plastic mat",
    "whiteboard marker",
    "action figure",
    "bunny chocolate",
    "decorative mirror",
    "tennis rackets",
    "footrest",
    "hanging hook",
    "napkin",
    "magazine holder",
    "banana",
    "paper puncher",
    "cd",
    "electric circuit board",
    "elephant toy",
    "cosmetic bottle",
    "wall mounted telephone",
    "watering bucket",
    "kitchen object",
    "mop cloth",
    "switchboard cover",
    "paint jar",
    "pull-up bar",
    "shower drain",
    "mount",
    "paper file",
    "oven glove",
    "midi controller",
    "hair brush",
    "head model",
    "laundry detergent",
    "packet",
    "teapot",
    "coaster",
    "fire alarm",
    "mirror lamp",
    "ceilng light",
    "water filter jug",
    "elephant decoration piece",
    "hand shower handle",
    "pan set",
    "fanny pack",
    "tissue paper",
    "thermos",
    "duster",
    "shower holder",
    "freezer",
    "plunger",
    "light cover",
    "circular tray",
    "pencil stand",
    "bedside counter",
    "game cd box",
    "surface cleaner",
    "lanyard",
    "moss pole",
    "electric box",
    "mop pad",
    "squeegee",
    "parcel",
    "hanging frame",
    "dish soap",
    "personal hygiene product",
    "bathroom slippers",
    "face mask",
    "stereo box",
    "game console controller",
    "file orginizer",
    "wire hider",
    "power board",
    "cleaning liquid",
    "bike helmet",
    "remote controller",
    "cutti̇ng board",
    "disinfectant dispenser",
    "internet socket",
    "hammer",
    "wlan router",
    "shower loofah",
    "vacuum flask",
    "ear muffs",
    "brochure",
    "kitchen roll",
    "headphones case",
    "plant pot coaster",
    "shorts",
    "table clock",
    "toilet flush",
    "ar tag",
    "joystick",
    "mailbox",
    "handle",
    "strainer",
    "cereal box",
    "potted plant",
    "game controller",
    "stamp",
    "liquid soap",
    "bread",
    "cream tube",
    "monitor holder",
    "dishwashing sponge",
    "hot bag",
    "intercom screen",
    "drainage",
    "bottle spray",
    "detergent bag",
    "milk carton",
    "vanity light",
    "snack bag",
    "scissors",
    "blind control rod",
    "power extender",
    "spool",
    "hole punch",
    "guitar pedal",
    "body weight scale",
    "figurine",
    "metal saw",
    "kitchen brush",
    "power brick",
    "soldering iron",
    "sandwich maker",
    "apple",
    "electrical board",
    "cable socket",
    "powerbank",
    "surface cleaning liquid",
    "glass jar",
    "scissor",
    "machine button",
    "phone tripod",
    "shower rod",
    "window handle",
    "soap container",
    "punching machine",
    "colander",
    "punching tool",
    "coffee pot",
    "flask",
    "hangers",
    "kitchen tap",
    "door knob",
    "flour bag",
    "night lamp",
    "multi socket",
    "arch folder",
    "hard drive",
    "coffee mug",
    "hangbag",
    "headphone bag",
    "toilet brush holder",
    "wine bottle",
    "cheese",
    "radio",
    "wall light",
    "dish",
    "marker storage",
    "food pot",
    "spray",
    "hanging light",
    "monitor light",
    "sticky note",
    "first aid box",
    "knob",
    "folder holder",
    "coffee jar",
    "saucer",
    "power supply",
    "socks",
    "hand vacuum",
    "dusting cloth",
    "juice box",
    "trivet",
    "dish washer soap",
    "silicon gun",
    "measuring spoon",
    "rubber water bag",
    "oragnizer",
    "monitor base",
    "lan port",
    "mushroom lamp",
    "marker eraser",
    "brief case",
    "blinds chain",
    "deodorant",
    "cleaner",
    "toiletry bottle",
    "circuit box",
    "door window",
    "voltage stabilizer",
    "glasses cover",
    "drilling machine",
    "tennis cap",
    "laptop cover",
    "phone stand",
    "electric socket",
    "usb hub",
    "leaf fan",
    "wallet",
    "magazine collector",
    "coffee",
    "star",
    "dish washing liquid",
    "paper package",
    "wall handle",
    "scrubber",
    "paper notebook",
    "toilet cleaner",
    "in-table power socket",
    "hand sanitizer",
    "intercom device",
    "emergency button",
    "chips can",
    "handwash",
    "wet tissue",
    "dried plant",
    "shaving foam",
    "ashtray",
    "tooth brush",
    "barcode scanner",
    "hand soap",
    "bunny decoration",
    "switch board",
    "rubber duck",
    "laptop charger",
    "dongle",
    "wall intercom",
    "funnel",
    "tumbler",
    "dishwashing soap",
    "guitar stand",
    "blowtorch",
    "toy car",
    "control switch",
    "toilet plunger",
    "paper note",
    "rugby ball",
    "wooden chest",
    "covered power socket",
    "hand washing liquid",
    "pot cover",
    "dishwashing liquid",
    "portable speaker",
    "takeout box",
    "tissue paper roll",
    "bluetooth speaker",
    "handle bar",
    "cleaning cloth",
    "shower wiper",
    "shower squeegee",
    "razor",
    "palm rest",
    "lotion",
    "spray can",
    "screwdriver",
    "pliers",
    "towel rack",
    "co detector",
    "product dispenser bottle",
    "tape roll",
    "dish brush",
    "moka pot",
    "sunblock",
    "stream deck",
    "card reader",
    "hair dryer holder",
    "stationery",
    "wall speaker",
    "shampoo",
    "beverage can",
    "paper weight",
    "hairbrush",
    "cell phone",
    "hammer holder",
    "glove",
    "mobile phone",
    "electrical tape",
    "sponge cloth",
    "card",
    "postit note",
    "glue bottle",
    "juice tetrapack",
    "pencil",
    "highlighter",
    "ceiling speaker",
    "light bulb",
    "grab rail",
    "kitchen light",
    "headphone holder",
    "product tube",
    "comb",
    "pi̇cture",
    "jump rope",
    "bar soap",
    "coarser",
    "electrical plug",
    "power plug",
    "coax outlet",
    "soap holder",
    "door stopper",
    "soap bar",
    "lint roller",
    "duct tape",
    "box lid",
    "tea packets",
    "toilet holder",
    "backdrop hook",
    "holder",
    "network outlet",
    "towel hanger",
    "table tennis racket",
    "cards",
    "pocket calculator",
    "button",
    "post-it",
    "wood stick",
    "note",
    "mask",
    "creamer packets",
    "wireless charger",
    "smartphone",
    "tooth paste",
    "coffee packets",
    "post it",
    "cigarette packet",
    "door hinge",
    "ladle",
    "stovetop",
    "receipt",
    "probe",
    "fan switch",
    "spoon",
    "dispenser",
    "hook",
    "cabbage",
    "lan",
    "whiteboard marker holder",
    "doorknob",
    "nose spray",
    "soap tray",
    "botttle",
    "correction fluid",
    "electrical outlet",
    "razor blade",
    "magnet",
    "vertical blind control",
    "cream bottle",
    "electrical adapter",
    "sticker",
    "datashow socket",
    "post it note",
    "earbuds",
    "wireless headphones",
    "whiteboard duster",
    "cabinet top",
    "cabinet door",
    "chair cushion",
    "acoustic guitar",
    "acoustic guitar case",
    "adaptor",
    "adjustable bench",
    "adjusting rod",
    "air conditioner remote",
    "air diffuser",
    "air freshener",
    "air humidifier",
    "air mattress",
    "air pump",
    "air ventilator",
    "alarm clock",
    "alcohol bottle",
    "alcoholic drinks",
    "alcove",
    "alcove bench",
    "amazon alexa",
    "arched ceiling",
    "audio amplifier",
    "audio equipment",
    "audio interface",
    "award",
    "award frame",
    "baby bassinet",
    "baby bean bag",
    "baby chair",
    "baby mattress",
    "baby musical crib",
    "backing paper pack",
    "backpacks",
    "backpag",
    "badge",
    "badminton racket bag",
    "bag of chips",
    "baguettes",
    "bakcpack",
    "baking pan",
    "baking paper roll",
    "baking sheet",
    "baking tray",
    "ball cart",
    "ballon",
    "baloons",
    "banquette",
    "bar cart",
    "basket contents",
    "basket drawer",
    "basketball basket",
    "baskets",
    "bath robe",
    "bath towel",
    "bathroom box",
    "bathroom cabinet drawer",
    "bathroom ceiling light",
    "bathroom clothes shelf",
    "bathroom divider",
    "bathroom door",
    "bathroom hook",
    "bathroom light",
    "bathroom mirror",
    "bathroom mirror lamp",
    "bathroom mirror panel",
    "bathroom rug",
    "bathroom stall partition",
    "bathroom tiled shelf",
    "bathroom tiled wall",
    "bathroom vent",
    "bathroom wall",
    "bathtub grab rail",
    "bathtub tap",
    "battery powered vacuum cleaner",
    "beach ball",
    "bean bag chair",
    "beanie",
    "bed board",
    "bed drawer",
    "bed sheets",
    "bedsheets",
    "bedside drawer unit",
    "beer crate",
    "beer pack",
    "belts",
    "bench back rest",
    "bench cushion",
    "bench power supply",
    "beverage bottle",
    "beverage bottles",
    "beverage cans",
    "beverage carton",
    "beverages",
    "bicycle helmet",
    "billiards table",
    "binders",
    "bio trash bin",
    "blackboard eraser",
    "blackboard stand",
    "blankets",
    "blender jug",
    "blinds roller",
    "blouse",
    "board eraser",
    "board game",
    "board games",
    "body lotion container",
    "body scrubber",
    "book stand",
    "boox",
    "botlle",
    "bottle cleaning brush",
    "bottle container",
    "bouquet",
    "bowls",
    "box container",
    "bread bag",
    "bread box",
    "bread knife",
    "bread loaf",
    "bread maker",
    "breadbox",
    "brick",
    "brochures",
    "broom handle",
    "broom head",
    "broomstick",
    "buckets",
    "bunkbed",
    "c",
    "cabinet ceilng",
    "cable container",
    "cable drum",
    "cable duck",
    "cable duct support",
    "cable duct supporters",
    "cable duct supports",
    "cable junction",
    "cable junction box",
    "cable strip",
    "cactus",
    "cafe curtain",
    "calander",
    "calender",
    "camera stand",
    "camping bag",
    "candles",
    "candy box",
    "cannister",
    "canopy bed",
    "carboard",
    "cardboard packing material",
    "cardboard tube",
    "carrier cart",
    "carrots",
    "carrying case",
    "cat food bowl",
    "cat play tower",
    "cat scratching post",
    "cds",
    "ceiling camp",
    "ceiling hanging lamp",
    "ceiling lamp shade",
    "ceiling lapm",
    "ceiling light fixture",
    "ceiling light rail",
    "ceiling object",
    "ceiling sprinkler",
    "ceiling ventilation panel",
    "ceiling ventilation valve",
    "cellphone",
    "central heating pipe",
    "central speaker",
    "cettel",
    "chair leg",
    "chalk board",
    "chalkboard",
    "charger head",
    "chewing gum",
    "chicken hat",
    "chimney",
    "chips",
    "chips bag",
    "chips box",
    "chocolate bar",
    "chocolate box",
    "chopsticks",
    "cigarette box",
    "cigarette pack",
    "clamp",
    "clamping lamp",
    "cleaner bottle",
    "cleaning agent bottle",
    "cleaning bucket",
    "cleaning product",
    "cleaning supply",
    "clipboard",
    "clithes",
    "clogs",
    "closet rod",
    "cloth bag",
    "cloth bags",
    "clothes basket",
    "clothes bin",
    "clothes box",
    "clothes dryer rack",
    "clothes drying rack",
    "clothes hanger rail",
    "clothes hanger rod",
    "clothes hanging rack",
    "clothes hanging rod",
    "clothes hook",
    "clothes iron",
    "clothes rail",
    "clothes rod",
    "clothes stander",
    "clothing",
    "clothing iron",
    "clothing rack",
    "clothng rail",
    "cnc machine",
    "coat hanger rack",
    "coat hook",
    "coat hooks",
    "coat wall rack",
    "coats",
    "coax outlets",
    "coax sockets",
    "coffee bean grinder",
    "coffee beans",
    "coffee capsules",
    "coffee cup",
    "compact wardrobe",
    "computer bag",
    "computer cabinet",
    "computer camera",
    "computer mouse",
    "computer screen",
    "condiment bottle",
    "conduit",
    "conjunction box",
    "container basket",
    "controller",
    "cooker",
    "cooking appliances",
    "cooking mittens",
    "cooking pot lid",
    "cooking utensil",
    "cooking utensils",
    "cookware",
    "corck board",
    "cord",
    "cord duct",
    "cord duct support",
    "corded landline",
    "corded telephone",
    "cordless vacuum cleaner",
    "corner bench",
    "cosmetic tissue",
    "cosmetic tube",
    "countertop appliances",
    "cover up panel",
    "cowboy hat",
    "cream",
    "creme",
    "crocs",
    "cube shelve",
    "cube shelves",
    "cubicle separator",
    "cucumber",
    "cups",
    "curling iron",
    "curtain blinds",
    "curtain holder",
    "curtain pull cord",
    "curtain roll",
    "curtain slider",
    "cushion cover",
    "cutlery stand",
    "cylindrical speaker",
    "cylindrical stool",
    "dart board",
    "darts board",
    "decoration centerpiece",
    "decoration lamp",
    "decorations",
    "decorative bowl",
    "decorative cloth",
    "decorative jar",
    "decorative mat",
    "decorative pillar",
    "decorative plant",
    "decorative table",
    "decorative tray",
    "decorative wall",
    "deodorant bottle",
    "deodorant can",
    "desk calendar",
    "desk chair",
    "desk devider",
    "desk divider",
    "desk mat",
    "desk mic",
    "desk organiser",
    "desk orginizer",
    "detergent box",
    "detergent packet",
    "detergent pods box",
    "digital camera",
    "digital piano",
    "digital piano cover",
    "digital piano stand",
    "dimmer switch",
    "dining table mats",
    "dinner table",
    "dinnerware",
    "disco ball",
    "disco light",
    "dish cloth",
    "dish container",
    "dish drying tray",
    "dish rag",
    "dish sponge",
    "dish sponges",
    "dish towel",
    "dishcloth",
    "dishcloths",
    "dishrag",
    "dishrags",
    "display",
    "display cabinet",
    "display case",
    "dj desk",
    "docking station",
    "document",
    "document binder",
    "document file folder",
    "document folder",
    "document rack",
    "document shredder",
    "dog bone",
    "dog toy",
    "dog toy rope",
    "door blocker",
    "door closer",
    "door clothes hooks",
    "door coat rack",
    "door hook",
    "door hooks",
    "door intercom",
    "door stoper",
    "door treshold",
    "doorbell chime",
    "doorframw",
    "doorstop",
    "double door",
    "drain stopper",
    "draw cord",
    "drawer cabinet",
    "drawer organizer",
    "drawstring pouch",
    "dress",
    "drink carton",
    "drinking fountain",
    "dropped ceiling",
    "drying basket",
    "drying machine",
    "dslr camera",
    "duct tape roll",
    "dumpster",
    "dust bin",
    "dust brush",
    "dust collector",
    "dustpan and brush",
    "earphones",
    "echo dot",
    "egg",
    "egg basket",
    "egg crate",
    "electric cabinet",
    "electric cable extender",
    "electric cooker",
    "electric fan",
    "electric kettle pad",
    "electric outlet",
    "electric panel",
    "electric panel door",
    "electric piano",
    "electric switch",
    "electric toorhbrush",
    "electric wiring",
    "electrical ducts",
    "electrical fan",
    "electrical socket",
    "electricity meter",
    "electronic breadboard",
    "electronic toothbrush",
    "electrucal duct",
    "emergency exit sign",
    "emergency sign",
    "end table",
    "energy meter",
    "entertainment center",
    "entryway organizer",
    "entryway shelf",
    "ergonomic pillow",
    "escape sign",
    "esd mat",
    "esd strap",
    "exercise bike",
    "exercise mat",
    "exhaust vent",
    "exhaustion fan",
    "extension board",
    "extension box",
    "extension plug",
    "external memory",
    "extractor fan",
    "eyeglasses",
    "face brick",
    "facemask",
    "facuet",
    "faucet handle",
    "file binders",
    "file box",
    "file folders",
    "fire destinguisher",
    "fire extinguisher case",
    "fire extinquisher",
    "first aid chart",
    "first-aid bag",
    "fitness mat",
    "flat screen display",
    "flatbed trolley",
    "flip chart",
    "flipflops",
    "floodlight",
    "floor panel",
    "floor vent",
    "floormat",
    "flor",
    "flower vase",
    "flush panel",
    "flush sensor",
    "flyswatter",
    "foam roller",
    "foil dispenser",
    "foldable bench",
    "foldable hanging closet",
    "foldable mattress",
    "folded blanket",
    "folded box",
    "folded cardboard boxes",
    "folded carton",
    "folded paper",
    "folded poster",
    "folded rug",
    "folded stool",
    "folded tablecloth",
    "folded towel",
    "folding bed",
    "folding desk",
    "folding door",
    "folding fan",
    "folding mattress",
    "folding stool",
    "food bag",
    "food jar",
    "food packaging",
    "food products",
    "food storage",
    "food supplies",
    "food supply",
    "food tray",
    "foodstuffs",
    "foosball board",
    "foot stool",
    "football",
    "football stand",
    "foset",
    "fosit",
    "frame window screen",
    "french door",
    "french window",
    "fridge magnet",
    "fruit basket",
    "fruit bowl",
    "fruit hanger",
    "fruits basket",
    "fryer",
    "frying pans",
    "fuse box",
    "fuse panel",
    "fusebox",
    "gamecontroller",
    "gamer chair",
    "gaming chair",
    "garbage bag roll",
    "garment bag",
    "glass bowl",
    "glass cup",
    "glass cups",
    "glass door",
    "glass table",
    "glass wiper",
    "glasses",
    "glasses holder",
    "golf rogue bag",
    "grape",
    "grated ceiling",
    "grated floor mat",
    "grated floor stand",
    "grater",
    "gripper",
    "guitar amplifier",
    "hair comb",
    "hair dryer cord",
    "hair straightener",
    "hairdryer attachment",
    "hall door",
    "hallway",
    "hammock",
    "hand bell",
    "hand dryer",
    "hand mixer",
    "hand sanitizer dispenser",
    "hand sanitizer stand",
    "hand soap bottle",
    "handheld vacuum cleaner",
    "handrail",
    "handsoap",
    "hanging calendar",
    "hanging chair",
    "hanging lamp",
    "hanging shelf",
    "hanging storage bin",
    "hanging towel",
    "head phones",
    "hearth",
    "heat pipe",
    "heat shield",
    "helf",
    "helping hands",
    "hifi system",
    "hiking pole",
    "hiking poles",
    "hob",
    "hood",
    "hoodie",
    "hot water bag",
    "humidifier",
    "hygiene products",
    "ice cube tray",
    "ice tray",
    "incense sticks",
    "industrial machine",
    "intercorm",
    "ironing machine",
    "ironing table",
    "item tray",
    "janitorial trolley",
    "joga mat",
    "jumper",
    "jumping blocs",
    "junction box",
    "kayak",
    "ketchup bottle",
    "kettlle",
    "key",
    "key reader",
    "keyboard piano",
    "khol",
    "kichen cabinet",
    "kitchen apron",
    "kitchen backsplash",
    "kitchen bar",
    "kitchen cabinet base",
    "kitchen cabinet top",
    "kitchen cabonet",
    "kitchen chimney",
    "kitchen container",
    "kitchen counter lamp",
    "kitchen floor",
    "kitchen hob",
    "kitchen hutch",
    "kitchen island",
    "kitchen knife",
    "kitchen lamp",
    "kitchen organizer",
    "kitchen paper",
    "kitchen paper roll",
    "kitchen paper rolls",
    "kitchen paper towel",
    "kitchen rack",
    "kitchen storage rack",
    "kitchen tiled floor",
    "kitchen tiled wall",
    "kitchen utensil holder",
    "kitchen utensils cup",
    "kitchen wall protector",
    "knives",
    "knives holder",
    "knives set",
    "knobs",
    "lab appliance",
    "lab cabinet",
    "lab incubator",
    "lab stool",
    "lamp foot switch",
    "lamp footswitch",
    "lamp supporter",
    "lamp switch",
    "landline phone",
    "landline socket",
    "landline telephone",
    "lantern",
    "laptop holder",
    "laptop pouch",
    "laptops",
    "large laundry basket",
    "lateral pulley",
    "lathe",
    "laundry",
    "laundry bag",
    "laundry detergent bag",
    "laundry detergent bottle",
    "laundry detergent pads",
    "laundry drying rack",
    "laundry machine",
    "laundy basket",
    "leak",
    "leftovers box",
    "leg rest stool",
    "lemons",
    "letter tray",
    "letter trays",
    "lever switch",
    "lever valve",
    "light dimmer",
    "light strip",
    "light swich",
    "light swicth",
    "light switch and power socket",
    "light switch and power sockets",
    "light swtich",
    "lightbulb",
    "liight switch",
    "lint roller refill",
    "liquid soap bottle",
    "liquid soap dispenser",
    "lock",
    "lockers",
    "loft",
    "long brush",
    "long pan",
    "loofah",
    "loth",
    "lotion bottle",
    "lounge pug",
    "low bookshelf",
    "lunch bag",
    "lunch box",
    "magnetic board",
    "make up product",
    "make up supplies",
    "make-up supply",
    "makeup bag",
    "makeup box",
    "makeup pen",
    "makeup set",
    "mantel clock",
    "manual forklift",
    "map",
    "map poster",
    "mattress topper",
    "mayonnaise bottle",
    "medal",
    "medals",
    "medication",
    "medicine bottle",
    "meeting booth",
    "meeting pod",
    "metal briefcase",
    "metal cup",
    "microphone holder",
    "mini pc",
    "mini sofa",
    "mirror panel lamp",
    "mirror shelf",
    "mixing bowl",
    "mobile tablet stand",
    "monitor arm",
    "monitor lamp",
    "mop bucket",
    "mop rag",
    "mosquito swatter",
    "motorcycle helmet",
    "mouse  mat",
    "mouse mat",
    "movement sensor",
    "moving dolly",
    "mugs",
    "multimeter",
    "murphy bed",
    "music box",
    "music equipment case",
    "music keyboard",
    "music record",
    "music stand",
    "napkin dispenser",
    "neck bolster",
    "neon light",
    "network switch",
    "newspapers",
    "nintendo switch",
    "o",
    "oil bottle",
    "oil diffuser",
    "olive oil bottle",
    "opaque window panel",
    "open box",
    "open wardrobe",
    "orange",
    "oranges",
    "organizer box",
    "orginizer",
    "ornamental box",
    "outdoor trash can",
    "oven mitt",
    "oven mitten",
    "oven mitts",
    "over door hooks",
    "overhead cabinet",
    "packets",
    "paint bucket",
    "pan lid",
    "panel door",
    "panel light",
    "pans",
    "pant",
    "pantry",
    "paper bags",
    "paper boxes",
    "paper container",
    "paper dispenser",
    "paper filers",
    "paper lamp",
    "paper napkin roll",
    "paper pag",
    "paper sign",
    "paper towel holder",
    "paper towel pack",
    "parallettes",
    "pasta box",
    "paste tube",
    "peeler",
    "pems",
    "pen jar",
    "pen pouch",
    "pen stand",
    "pencilcase",
    "pendant lamp",
    "pensil case",
    "pepper container",
    "perfume bottle",
    "pet bed",
    "pet feeding plates",
    "pet food bowl",
    "pet food container",
    "pet food tray",
    "pet mat",
    "pet water dispenser",
    "phone charger",
    "phone charger]",
    "phone holder",
    "phone line outlet",
    "photograph",
    "piano bench",
    "piano foot pedal",
    "piano stand",
    "picture card",
    "picture frames",
    "picutre",
    "pillowcase",
    "pillows",
    "pin board",
    "ping pong paddle",
    "piping",
    "pissoir",
    "planks",
    "plant pot holder",
    "plant saucer",
    "plant stand",
    "plants",
    "plastic bags",
    "plastic basin",
    "plastic basket",
    "plastic bin",
    "plastic bucket",
    "plastic cup",
    "plastic foil box",
    "plastic food container",
    "plastic packet",
    "plastic plant",
    "plastic sack",
    "plastic stool",
    "plastic storage basket",
    "plastic storage baskets",
    "plastic wall container",
    "plastic wall panel",
    "plastic wall shelf",
    "plastic washbasin",
    "plastic wrap",
    "plastic wrap pack",
    "plate coaster",
    "plate flush",
    "plate of food",
    "platform",
    "platform dolly",
    "playstation",
    "pocket tissue",
    "pole",
    "pool cue",
    "pool cue holder",
    "pool stick holder",
    "pool table",
    "portable heater",
    "portable light",
    "portable vacuum cleaner",
    "post it notes",
    "poster rail",
    "poster stand",
    "pot holder",
    "pot rolling tray",
    "pots",
    "pouches",
    "power bank",
    "power cube",
    "power extension cable",
    "power oulet",
    "power outlets",
    "power switch box",
    "power switches",
    "pride flag",
    "pringles can",
    "printer cutter",
    "printing paper",
    "projector rail",
    "puch",
    "pullover",
    "pullup bar",
    "punching bag",
    "rack shelf",
    "racquet",
    "racquet bag",
    "rags",
    "rail shelf",
    "range",
    "recessed wardrobe",
    "record player",
    "refillable water bottle",
    "refirgerator",
    "regulator",
    "relaxing chair",
    "reusable plastic bag",
    "reusable shopping bag",
    "reusable shopping bags",
    "reusable water bottle",
    "ribbon",
    "rice bag",
    "ringlight",
    "rj45 outlet",
    "rj45 outlets",
    "robe",
    "robes",
    "robot",
    "robotic arm",
    "rock",
    "roll",
    "roll of tape",
    "rolled blinds",
    "rolled mat",
    "rolled mattress",
    "roller blind",
    "roller blinds pull cord",
    "roller shutter",
    "roller skate",
    "roller tray",
    "rolling pin",
    "rolling shelf",
    "roman chair",
    "room divider rail",
    "room freshener",
    "room partition",
    "round chair",
    "round pouch",
    "round table",
    "rubber glove",
    "rubber heating pad",
    "rubik's cube",
    "sac",
    "safety bollard",
    "safety poster",
    "salt",
    "salt container",
    "salt shaker",
    "sandwich bread",
    "sanitary bag",
    "sanitary bag dispenser",
    "sanitary product",
    "santa hat",
    "satchel bag",
    "satchels",
    "sauce bottle",
    "scrap carton",
    "scroll",
    "seasoning pot",
    "security cam",
    "security camera",
    "separation wall",
    "service trolley",
    "serving tray",
    "sewing machine",
    "shades",
    "shades roller",
    "shades slider",
    "shampoo bottles",
    "shampoo dispenser",
    "shawl",
    "shelf contents",
    "shelf rail",
    "shelving unit",
    "shirts",
    "shisha",
    "shoe horn",
    "shoe mat",
    "shoe tray",
    "shoe wall rack",
    "shoebox",
    "show curtain rod",
    "shower caddy",
    "shower cap",
    "shower control",
    "shower curtain rail",
    "shower door",
    "shower ewall",
    "shower gel bottle",
    "shower head mount",
    "shower pipe",
    "shower puff",
    "shower rack",
    "shower rail",
    "shower rod handle",
    "shower shelf",
    "shower sponge",
    "shower wal",
    "shutter box",
    "shwer curtain rail",
    "single couch",
    "sink brush",
    "sink countertop",
    "sink shelf",
    "ski",
    "ski boots",
    "ski goggles",
    "ski pole",
    "ski poles",
    "ski rack",
    "ski sticks",
    "skiing goggles",
    "skiing shoe",
    "skin care product",
    "skis",
    "sleep mask",
    "sleeping bag",
    "slide bar",
    "sliding blackboard track",
    "sliding door rail",
    "sliding glass door",
    "sliding window",
    "sling bag",
    "smal broom",
    "small appliance",
    "small bag",
    "small bookshelf",
    "small bowl",
    "small wardrobe",
    "small whiteboard",
    "smartboard",
    "smartphone holder",
    "smoke detectors",
    "snack",
    "sneaker",
    "snow sled",
    "snowboard",
    "snowglobe",
    "soap basket",
    "soap dispensers",
    "sock",
    "socket switch",
    "soda stream",
    "sofa cover",
    "sofa module",
    "sofa pillow",
    "soldering station",
    "sombrero",
    "sound absorbing panel",
    "space heater",
    "spatula",
    "spectacle case",
    "spectacles",
    "spectacles case",
    "spice",
    "spice bottle",
    "spice container",
    "spice jar",
    "spices",
    "spill mat",
    "spray bottles",
    "square conduit",
    "square plastic conduit",
    "stack of stools",
    "stacked chairs",
    "stair railing",
    "stair railling",
    "staircase",
    "stall door",
    "stand mixer",
    "standing calendar",
    "standing coat rack",
    "standing mirror",
    "standing podium",
    "standing speaker",
    "standing whiteboard",
    "stationaries",
    "stationary",
    "stationary cup",
    "stationery container",
    "stationery rack",
    "stationery tray",
    "steam iron",
    "step ladder",
    "stepstool",
    "stick vacuum cleaner",
    "stock pot",
    "stool bench",
    "storage basket",
    "storage bench",
    "storage chest",
    "storage closet",
    "storage grid",
    "storage organizer",
    "storage roller cart",
    "storage stool",
    "storage tank",
    "stove hood",
    "stove top",
    "straightening iron",
    "strip",
    "structural column",
    "structural pillar",
    "stuffed toys",
    "styrofoam",
    "sunglasses",
    "supermarket catalog",
    "surface mount raceway",
    "sweatpants",
    "swtich",
    "t-shirt",
    "table calander",
    "table decoration",
    "table leg",
    "table mirror",
    "table tennis bat",
    "tables",
    "tablet stand",
    "tableware",
    "tall table",
    "tapestry",
    "tarpaulin",
    "tea cup",
    "tea station",
    "teakettle",
    "telephone line socket",
    "telescope",
    "tempering valve",
    "tennis bag",
    "tennis ball",
    "tennis racquet",
    "tiled floor",
    "tiled wall",
    "tin box",
    "tissue bag",
    "tissue pack",
    "tissue roll",
    "toe kick",
    "toilet brush bowl",
    "toilet cabinet",
    "toilet flush buttons",
    "toilet paper pack",
    "toilet paper stack",
    "toiletries",
    "toiletry bag",
    "toiletry basket",
    "toliet paper",
    "toliet paper rolls",
    "tongs",
    "tool cabinet",
    "tool trolley",
    "toolboxes",
    "tools storage",
    "tooth cleaning product",
    "tooth paste tube",
    "toothbrushes",
    "toothpaste bottle",
    "toothpaste tube",
    "top loading washing machine",
    "towel rail",
    "towel rod",
    "track system",
    "trash",
    "trash bag pack",
    "trash bags",
    "trash can lid",
    "trash container",
    "trashbin",
    "travel backpack",
    "travel bag",
    "travel suit bag",
    "travelling bag",
    "trenchcoat",
    "triangle flags",
    "tripod bag",
    "tripods",
    "trolley bag",
    "trunk",
    "tube container",
    "tube light",
    "tv cabinet",
    "tv controller",
    "typewriter",
    "umbrella can",
    "umbrella holder",
    "utensil canister",
    "utensil cup",
    "utensil rack",
    "utensil tray",
    "utility box",
    "utility cart",
    "utility room door",
    "vacuum cleaner head",
    "vacuum robot",
    "vape pen",
    "vegetable box",
    "vegetables",
    "ventilation fan",
    "ventilation shaft",
    "vise",
    "vottle",
    "waffle maker",
    "wal",
    "walking cane",
    "wall decoration",
    "wall flush",
    "wall frame",
    "wall hanging basket",
    "wall hanging rack",
    "wall hook rack",
    "wall mirror",
    "wall mounted coat rack",
    "wall mounted organizer",
    "wall mounted table",
    "wall mounted thermostat",
    "wall organizer",
    "wall panel",
    "wall phone",
    "wall rack",
    "wall shelf unit",
    "wall sign",
    "wall telephone sockets",
    "wall thermostat",
    "wall/other room",
    "wardrobe box",
    "wardrobe frame",
    "wardrobe rack",
    "wasching machine",
    "washcloth",
    "washing powder",
    "watch",
    "water boittle",
    "water container",
    "water cooler",
    "water pot",
    "water sweeper",
    "weight",
    "weight bar",
    "wetmop",
    "wheelbarrow",
    "wheeled chair",
    "wheeled side table",
    "wheeled storage cabinet",
    "whiskey bottle",
    "whiteboard markers",
    "whiteboard rag",
    "wicket door",
    "window casing",
    "window cleaning brush",
    "window counter",
    "window cover panel",
    "window door",
    "window lintel",
    "window shutters",
    "window sign",
    "window wiper",
    "windows",
    "wine bottles",
    "wiper",
    "wire basket",
    "wire junction",
    "wire spool",
    "wire stripper",
    "wires",
    "wood block",
    "wood branch",
    "wooden basket",
    "wooden beam",
    "wooden bench",
    "wooden block",
    "wooden box",
    "wooden panel",
    "wooden panel window",
    "wooden spoon",
    "woofer speaker",
    "wrist rest",
    "yoga brick",
    "yoga mat band",
    "yogurt cup",
    "zip up hoodie",
]

architectural_elements = [
    "arched ceiling", "balcony door", "bathroom door", "bathroom floor", "bathroom tiled wall", "bathroom wall",
    "brick wall", "ceiling camp", "ceiling lapm", "ceiling pipe", "ceiling sprinkler", "ceiling vent",
    "ceiling ventilation panel", "ceiling ventilation valve", "ceiling ventilator", "chimney", "climbing wall", "column",
    "cubicle door", "decorative pillar", "decorative wall", "door", "door blocker", "door intercom", "door vent",
    "door window", "doorbell chime", "doorframw", "doorway", "double door", "dropped ceiling", "duct",
    "electric panel door", "fireplace", "floor cushion", "floor mat", "floor mounted air conditioner", "floor panel",
    "floor scrubber", "floor vent", "folding door", "frame window screen", "french door", "french window",
    "garage door", "glass door", "glass wall", "grated ceiling", "hall door", "indoor crane", "kitchen ceiling",
    "kitchen floor", "kitchen tiled floor", "kitchen tiled wall", "kitchen wall", "opaque window panel", "panel door",
    "partition wall", "pillar", "railing", "raised floor", "roof", "separation wall", "sill", "sliding door",
    "sliding door frame", "sliding door rail", "sliding glass door", "sliding window", "stair", "stair railing",
    "stair railling", "staircase", "staircase railing", "stairs", "stall door", "steel beam", "structural column",
    "structural pillar", "suspended ceiling", "tile wall", "tiled floor", "tiled wall", "utility room door", "vent",
    "wall beam", "wall board", "wall cord cover", "wall flush", "wall frame", "wall hanging", "wall intercom",
    "wall mounted thermostat", "wall outlet", "wall strip", "wall telephone sockets", "wall thermostat", "wall unit",
    "wall/other room", "wicket door", "window", "window blind", "window casing", "window counter",
    "window cover panel", "window door", "window head", "window lintel", "window pane", "window sill", "window wiper",
    "windowframe", "windows", "wooden beam", "wooden panel window"
]
cluster_custom_labels = {
    1: "Electronic Displays and Connection Devices",
    4: "Containers, Bags and Storage Items",
    0: "Storage Furniture and Shelving Units",
    39: "Liquid Containers and Dispensers",
    26: "Seating and Bedding Furniture",
    31: "Clothing and Wearable Items",
    8: "Doors, Frames and Panels",
    9: "Window Coverings and Rails",
    10: "Lighting Fixtures and Mirrors",
    2: "HVAC Systems and Ventilation",
    -1: "Miscellaneous Items (Noise)",
    45: "Cleaning Tools and Equipment",
    30: "Household Machines and Appliances",
    32: "Cleaning Textiles and Paper Products",
    29: "Plants and Cookware",
    49: "Drinkware and Food Containers",
    7: "Bathroom and Plumbing Fixtures",
    3: "Tables",
    40: "Carts and Trolleys",
    34: "Audio Equipment and Musical Instruments",
    36: "Cooking Appliances",
    42: "Mats and Rugs",
    47: "Hooks and Hangers",
    20: "Trays and Serving Items",
    18: "Misspelled Objects",
    27: "Toys and Figurines",
    46: "Sports Equipment",
    37: "Fans",
    41: "Baskets",
    22: "Decorative Items",
    48: "Switches and Controls",
    71: "Writing Instruments",
    6: "Exercise Bars and Weights",
    14: "Room Dividers and Partitions",
    25: "Plates and Scales",
    56: "Alarms and Intercoms",
    89: "Fruits and Vegetables",
    59: "Headphones and Audio Accessories",
    60: "Cooking Pans",
    19: "Wooden Beams and Posts",
    21: "Toilet Fixtures",
    68: "Kitchen Utensils and Appliances",
    102: "Eating Utensils",
    44: "Coffee Equipment",
    81: "Gloves and Oven Mitts",
    5: "Countertops and Kitchen Surfaces",
    90: "Media Players and Discs",
    97: "Eyewear",
    67: "Tubes and Cylindrical Containers",
    100: "Bread and Baked Goods",
    12: "Ceiling Elements",
    80: "Cameras and Imaging Devices",
    88: "Notes and Sticky Papers",
    16: "Signs and Signage",
    35: "Refrigeration Appliances",
    43: "Dishwashers and Draining Equipment",
    11: "Structural Columns and Pillars",
    54: "Textiles and Fabrics",
    63: "Spray Bottles and Dispensers",
    84: "Laptop Accessories",
    94: "Wipers and Cleaning Tools",
    13: "Floor Surfaces",
    24: "Basins and Drains",
    53: "Umbrellas and Stands",
    61: "Binders and Binding Equipment",
    73: "Print Media and Magazines",
    74: "Calendars",
    77: "Cards and Card Readers",
    85: "First Aid Equipment",
    93: "Chargers and Power Accessories",
    15: "Backsplash and Wall Coverings",
    17: "Fireplaces and Chimneys",
    23: "Meters and Measurement Devices",
    33: "Carpets and Rugs",
    50: "Fire Safety Equipment",
    55: "Smart Devices and Robotics",
    58: "Brooms and Sweeping Tools",
    98: "Food Items",
    105: "Snack Packages",
    106: "Awards and Medals",
    28: "Entertainment Devices",
    38: "Photos and Pictures",
    52: "Computer Input Devices",
    65: "Clocks",
    66: "Canisters and Containers",
    69: "Musical Instrument Cases",
    72: "Gas Cylinders",
    83: "Mixers",
    87: "Power Banks and Strips",
    91: "Egg Products",
    99: "Window Shades",
    108: "Makeup Products",
    51: "Tripods",
    57: "Grills",
    62: "Towel Heaters",
    64: "Locks and Security Devices",
    70: "Cooking Hobs",
    75: "Charts and Flip Charts",
    76: "Routers and Networking",
    78: "Milk and Beverage Cartons",
    79: "Scientific Instruments",
    82: "Flags",
    86: "Cable Spools",
    92: "Candles",
    95: "Mounts and Brackets",
    96: "Heating and Cooling Pads",
    101: "Dish Items",
    103: "Organizers and Graters",
    104: "Docking Stations and Hubs",
    107: "Misspelled Items",
    109: "Pool Cues",
    110: "Salt Containers"
}

# 1. Get Embeddings
print("Loading sentence transformer model and encoding class names...")
model = SentenceTransformer("all-mpnet-base-v2")
embeddings = model.encode(class_names, show_progress_bar=True)
print(f"Shape of embeddings: {embeddings.shape}")

# 2. t-SNE for Dimensionality Reduction
print("Performing t-SNE dimensionality reduction...")
tsne = TSNE(n_components=2, random_state=42, perplexity=30, max_iter=2000, n_jobs=-1)
tsne_results = tsne.fit_transform(embeddings)
print(f"Shape of t-SNE results: {tsne_results.shape}")

# 3. DBSCAN Clustering
print("Performing DBSCAN clustering...")
dbscan = DBSCAN(eps=3, min_samples=3)
clusters = dbscan.fit_predict(tsne_results)
print(f"Cluster labels: {clusters}")

n_clusters_ = len(set(clusters)) - (1 if -1 in clusters else 0)
n_noise_ = list(clusters).count(-1)
print(f"Estimated number of clusters: {n_clusters_}")
print(f"Estimated number of noise points: {n_noise_}")

# --- Calculate cluster representative names ---
cluster_representative_names = {}  # Stores {cluster_id: representative_name_string}
unique_cluster_ids_for_reps = set(clusters)

# After performing DBSCAN clustering but before creating visualization

# 1. First create the cluster-to-classes mapping (original direction)
clusters_to_classes = {}
for idx, cluster_id in enumerate(clusters):
    if cluster_id not in clusters_to_classes:
        clusters_to_classes[cluster_id] = []
    clusters_to_classes[cluster_id].append(class_names[idx])

# 2. Create the reverse mapping (classes-to-cluster)
classes_to_cluster = {}
for idx, class_name in enumerate(class_names):
    classes_to_cluster[class_name] = clusters[idx]

# Export classes-to-cluster mapping
with open("classes_to_cluster.txt", "w") as f:
    f.write("CLASSES TO CLUSTER MAPPING\n")
    f.write(f"Total classes: {len(class_names)}, Total clusters: {n_clusters_}\n\n")
    
    # Sort alphabetically by class name
    for class_name in sorted(classes_to_cluster.keys()):
        cluster_id = classes_to_cluster[class_name]
        
        # Get representative name for the cluster if it's not noise
        if cluster_id == -1:
            cluster_name = "Noise"
        else:
            cluster_name = cluster_representative_names.get(cluster_id, f"Cluster {cluster_id}")
        
        f.write(f"{class_name}: Cluster {cluster_id} ({cluster_name})\n")

print(f"Classes to cluster mapping saved to 'classes_to_cluster.txt'")

# Also fix the cluster-to-classes export
with open("cluster_to_classes.txt", "w") as f:
    f.write(f"CLUSTER TO CLASSES MAPPING\n")
    f.write(f"Total clusters: {n_clusters_}, Noise points: {n_noise_}\n\n")
    
    # Sort clusters by size (number of classes)
    sorted_cluster_ids = sorted(
        clusters_to_classes.keys(), 
        key=lambda cid: len(clusters_to_classes[cid]), 
        reverse=True
    )
    
    for cluster_id in sorted_cluster_ids:
        classes = clusters_to_classes[cluster_id]
        
        if cluster_id == -1:
            f.write(f"CLUSTER: Noise (ID: -1)\n")
        else:
            representative = cluster_representative_names.get(cluster_id, f"Cluster {cluster_id}")
            f.write(f"CLUSTER: {representative} (ID: {cluster_id})\n")
        
        f.write(f"Size: {len(classes)} classes\n")
        f.write("Classes:\n")
        
        # Write classes in alphabetical order
        for class_name in sorted(classes):
            f.write(f"- {class_name}\n")
        
        f.write("\n" + "-"*50 + "\n\n")

for cluster_id_val in unique_cluster_ids_for_reps:
    if cluster_id_val == -1:  # Skip noise points
        cluster_representative_names[cluster_id_val] = "Noise"
        continue

    member_indices = np.where(clusters == cluster_id_val)[0]
    if len(member_indices) == 0:
        continue

    member_tsne_coords = tsne_results[member_indices]
    centroid = np.mean(member_tsne_coords, axis=0)  # Centroid in t-SNE space

    # Find the member closest to the centroid
    distances_to_centroid = np.sum((member_tsne_coords - centroid) ** 2, axis=1)
    closest_member_local_idx = np.argmin(distances_to_centroid)
    representative_member_global_idx = member_indices[closest_member_local_idx]
    representative_name = class_names[representative_member_global_idx]

    cluster_representative_names[cluster_id_val] = representative_name

# 4. Create Interactive Plot with Plotly
print("Generating interactive plot...")

# Prepare data for Plotly DataFrame
df_data = {
    "x": tsne_results[:, 0],
    "y": tsne_results[:, 1],
    "class_name": class_names,
    "cluster_id_numeric": clusters,
}
df = pd.DataFrame(df_data)

# Create a hover text string for each point and map representative names
hover_texts = []
cluster_display_names = []

for i in range(len(df)):
    point_class_name = df["class_name"].iloc[i]
    point_cluster_id = df["cluster_id_numeric"].iloc[i]

    custom_label = cluster_custom_labels.get(point_cluster_id, f"Cluster {point_cluster_id}")

    cluster_info_str = f"Cluster: {custom_label} (ID: {point_cluster_id})"
    cluster_display_names.append(f"{custom_label} (ID: {point_cluster_id})")

    hover_texts.append(f"<b>Label:</b> {point_class_name}<br><b>{cluster_info_str}</b>")

df["hover_text"] = hover_texts
df["cluster_display_name"] = cluster_display_names

# Create the scatter plot
# ...existing code...

# Create the scatter plot
fig = px.scatter(
    df,
    x="x",
    y="y",
    color="cluster_display_name",  # Color by the representative name + ID string
    color_discrete_sequence=px.colors.qualitative.Bold,  # Use Bold color palette for better distinction
    custom_data=["hover_text"],  # Pass the fully formatted hover text
    labels={"cluster_display_name": "Cluster Information"},  # Legend title
    title=(
        f"Interactive t-SNE of {len(class_names)} class names with DBSCAN<br>"
        f"(eps={dbscan.eps}, min_samples={dbscan.min_samples}) - Clusters: {n_clusters_}, Noise: {n_noise_}"
    ),
)

# Customize hover information
fig.update_traces(
    hovertemplate="%{customdata[0]}<extra></extra>"  # Use custom_data for hover, <extra> removes trace info
)

fig.update_layout(
    xaxis_title="t-SNE Dimension 1",
    yaxis_title="t-SNE Dimension 2",
    legend_title_text="Cluster (Representative Name & ID)",
    height=800,
)

# Add cluster labels to the plot (for the largest clusters)
# First calculate centroids for each cluster
centroids = {}
unique_clusters = df['cluster_id_numeric'].unique()
for cluster_id in unique_clusters:
    if cluster_id == -1:  # Skip noise points
        continue
    cluster_points = df[df['cluster_id_numeric'] == cluster_id]
    centroid_x = cluster_points['x'].mean()
    centroid_y = cluster_points['y'].mean()
    cluster_size = len(cluster_points)
    centroids[cluster_id] = {
        'x': centroid_x,
        'y': centroid_y,
        'size': cluster_size,
        'name': cluster_representative_names[cluster_id]
    }

# Sort clusters by size and label the top 15
# ...existing code...

# Sort clusters by size and label the top 15
sorted_clusters = sorted(centroids.items(), key=lambda x: x[1]['size'], reverse=True)

for i, (cluster_id, info) in enumerate(sorted_clusters[:15]):
    # Alternate arrow directions based on index to reduce overlap
    arrow_direction = 40 if i % 2 == 0 else -40
    arrow_direction_y = -30 if i % 3 == 0 else (-50 if i % 3 == 1 else -10)
    
    fig.add_annotation(
        x=info['x'],
        y=info['y'],
        text=f"{info['name']} (ID: {cluster_id}, size: {info['size']})",  # Added size info
        showarrow=True,
        arrowhead=2,
        arrowsize=1,
        arrowwidth=2,
        arrowcolor="#636363",
        ax=arrow_direction,  # Vary horizontal position
        ay=arrow_direction_y,  # Vary vertical position
        font=dict(
            family="Arial",
            size=12,
            color="black"
        ),
        bgcolor="rgba(255, 255, 255, 0.8)",
        bordercolor="black",
        borderwidth=1,
        borderpad=4,
    )

# Also label the architectural elements in a different style
# Use a list to track label positions to avoid overlapping
used_positions = []
for idx, arch_element in enumerate(architectural_elements[:10]):
    if arch_element in df['class_name'].values:
        element_idx = df.index[df['class_name'] == arch_element][0]
        # Vary arrow directions for architectural elements too
        ax_dir = 20 + (idx % 3) * 15  # Stagger horizontally
        ay_dir = -20 - (idx % 4) * 10  # Stagger vertically
        
        fig.add_annotation(
            x=df.loc[element_idx, 'x'],
            y=df.loc[element_idx, 'y'],
            text=arch_element,
            showarrow=True,
            arrowhead=1,
            arrowsize=1,
            arrowwidth=1.5,
            arrowcolor="#0000CD",
            ax=ax_dir,
            ay=ay_dir,
            font=dict(
                family="Arial",
                size=11,
                color="#0000CD",
                weight="bold"
            ),
            bgcolor="rgba(255, 255, 255, 0.9)",
            bordercolor="#0000CD",
            borderwidth=1,
            borderpad=3,
        )

# Save to HTML file
output_filename = "interactive_tsne_visualization.html"
fig.write_html(output_filename)
print(f"Interactive plot saved as {output_filename}")
print("You can open this HTML file in your web browser.")

# ...existing code...

# After creating the figure and before writing to HTML

# Save high-resolution static image (1000 DPI)
print("Generating high-resolution image (1000 DPI)...")

# Calculate appropriate dimensions for 1000 DPI
# A standard letter size is 8.5 x 11 inches, we'll use similar proportions
width_inches = 12  # 12 inches wide
height_inches = 10  # 10 inches tall

# Convert to pixels at 1000 DPI
width_px = width_inches * 1000
height_px = height_inches * 1000

# Export high-res image
img_filename = "tsne_visualization_1000dpi.png"
fig.write_image(
    img_filename,
    width=width_px,
    height=height_px,
    scale=1,  # Already accounted for in width_px and height_px
)
print(f"High-resolution image saved as {img_filename}")

# Continue with HTML export
output_filename = "interactive_tsne_visualization.html"
fig.write_html(output_filename)
print(f"Interactive plot saved as {output_filename}")
print("You can open this HTML file in your web browser.")